# Fill in your LLM & API key info
NVIDIA_API_KEY = "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"
NVIDIA_API_BASE = "https://integrate.api.nvidia.com/v1"
NVIDIA_MODEL = "nvidia/llama-3.3-nemotron-super-49b-v1.5"    # Model from build.nvidia.com